# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2-snapshot-6
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
# Fabric API
fabric_api_version=0.148.1+26.2

# Mod Properties
mod_version=1.2.16+MC26.2-snapshot-6
maven_group=com.mattymatty.audio_priority
archives_base_name=audio_engine_tweaks

# Dependencies
modmenu_version=18.0.0-alpha.8
